### ISSUE TITLE
alert: "Could not find input[name=params] in your form" on submission

### ISSUE THREAD

**Issue by mmichael0413** [transloadit/rails-sdk#41]
I followed the tutorial but can't get the form to submit without getting the aforementioned alert. After I click "ok", Transloadit quickly throws `INVALID_FORM_DATA: bad form data, cannot parse`.

My app is using `Rails 4.1.4` and `jquery-rails 2.1.4`.

Here's my form:

    = form_for @profile, url: community_add_photo_path(@profile), html: {id: 'photo_form'} do |f|
      = render 'shared/error_messages', object: f.object
      = transloadit :profile_photo
      = hidden_field_tag 'transloadit_template', 'profile_photo'

      %table.list
        %tr
          %td.faded.label Photo Filename
          %td= f.file_field :photo, required: true
        %tr
          %td
          %td= f.submit 'Upload'

    = transloadit_jquerify :photo_form, wait: true

And my `transloadit.yml` file:

    development:
      jquery_sdk_version: 'latest'
      auth:
        key:      'key'
        secret:   'secret'
        duration: 1800 # 30 minute validity period for signed upload forms

      templates:
        profile_photo:
          steps:
            resize:
              height: 256
              resize_strategy: 'fillcrop'
              robot: '/image/resize'
              width: 256
            store:
              bucket: 'bucket-name'
              key: 'key'
              path: 'temp/${assembly.id}/${file.name}'
              robot: '/s3/store'
              secret: 'secret'

Any suggestions? Thanks!

**Comment by rmehner** [comment]
Sorry that we've overlooked this :-/ Hope you got it working.
