### ISSUE TITLE
Rails-sdk compatible with rails 2.3

### ISSUE THREAD

**Issue by iotmobile** [transloadit/rails-sdk#46]
My app is using ruby 1.8.7 and rails 2.3.5. Does the current version of rails-sdk support rails 2.3? If it is not, could you give me a link of older version which compatible with rails 2.3?

**Comment by rmehner** [comment]
Hey there, the library is using Engines, which is a feature that was introduced to Rails with version 3.0. There is no version that supports Rails 2.3, sorry!

If you look through the source, you'll see that the library isn't that much lines of code, so you might be able to get something on your own which works for 2.3 :) Let us know if you have any questions about that and have a great day!
