### ISSUE TITLE
Loosen dependency on mime-types gem to make compatible with Rails 5

### ISSUE THREAD

**Issue by townhouse** [transloadit/rails-sdk#48]
Thanks for your work on this gem :)

rails-sdk has dependency on 'mime-types', '~> 2.99'
Rails 5 depends on mime-types (3.1)

Can you loosen the dependency so rails-sdk can be used in a Rails 5 app?

**Comment by einzige** [comment]
@townhouse can you please check out this: https://github.com/transloadit/rails-sdk/pull/49 and replicate the issue. I don't see any problems with mime-types.

**Comment by rmehner** [comment]
This has been fixed with #49.
