### ISSUE TITLE
Cant convert a video to mp4 and keep its size

### ISSUE THREAD

**Issue by mzaragoza** [transloadit/rails-sdk#57]
I am trying get a video out as a mp4 and I need to keep the original proportions. 

This is my current Template

```
{
  "steps": {
    "encode": {
      "use": ":original",
      "robot": "/video/encode",
      "ffmpeg_stack": "v2.2.3",
      "result": true,
      "preset": "ipad-high",
      "ffmpeg_params": {
        "s": "-1x-1"
      }
    },
    "thumbnails": {
      "use": ":original",
      "robot": "/video/thumbs"
    },
    "store": {
      "use": "encode",
      "robot": "/s3/store",
      "key": "xxxxxxxxxxx",
      "secret": "xxxxxxxxxxx",
      "bucket": "xxxxxxxxxxx"
    }
  }
}
```

**Comment by rmehner** [comment]
Hey @mzaragoza,

thanks for writing. Unfortunately this is completely unrelated to the rails sdk, as it passes the options to Transloadit and then stuff happens on their servers. Pinging @kvz @tim-kos, can you help this fella out? :)

**Comment by kvz** [comment]
Hi! Yes please use the speech bubble on our website or email support@transloadit.com. We take pride in very fast response times and/so I'm sure we can get this sorted it quickly for you.

Thanks Robin for the mention! ❤️
