### ISSUE TITLE
NoMethodError - undefined method `before_filter' with Rails > 5.1 applications

### ISSUE THREAD

**Issue by spaghetticode** [transloadit/rails-sdk#58]
`before_filter` has been deprecated since Rails 5.1 in favor of `before_action`, so at least module `Transloadit::Rails::ParamsDecoder` which is referenced in the README should be updated to play nice also with recent/updated applications.

**Comment by rmehner** [comment]
This will be a good candidate for a breaking change that #63 implies.

**Comment by juliangruber** [comment]
Isn't this taken care of already?

https://github.com/transloadit/rails-sdk/blob/28b761b9a0032efb7a597bfaa15387f4ff37c618/lib/transloadit/rails/params_decoder.rb#L7-L11

**Comment by rmehner** [comment]
Seems so.
