### ISSUE TITLE
Update default jQuery SDK version to v3-latest

### ISSUE THREAD

**Issue by spaghetticode** [transloadit/rails-sdk#59]
The default jQuery SDK version in  `transloadit.yml` file is `v2-latest` but `v3-latest` is available. 

As per jquery SDK [readme](https://github.com/transloadit/jquery-sdk/blob/master/README.md) `v3-latest` is the __recommended version to use__

**Comment by kvz** [comment]
Sorry for the long wait here. I bet it's no longer relevant - still - I noticed this was being worked on in #60, and I'll see if we can get that merged.

**Comment by kiloreux** [comment]
Fixed in #62
